import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {EventEmitter} from 'node:events';
import sharp from 'sharp';
import embeddedDocs from '../src/extension.ts';
import {codeModeDocumentTool} from '../integrations/code-mode.ts';
test('pi image content, branch scope restore/clear, and code-mode shared scope',async t=>{
 const cwd=await mkdtemp(join(tmpdir(),'pi-docs-extension-'));t.after(()=>rm(cwd,{recursive:true,force:true}));
 await writeFile(join(cwd,'manual.txt'),'REGISTER ABC_CTRL at 0x40001000');
 const tools=new Map<string,any>(),commands=new Map<string,any>(),handlers=new Map<string,any[]>(),branch:any[]=[];
 const bus=new EventEmitter();
 const pi:any={events:bus,registerTool:(x:any)=>tools.set(x.name,x),registerCommand:(n:string,x:any)=>commands.set(n,x),
 on:(n:string,fn:any)=>handlers.set(n,[...(handlers.get(n)??[]),fn]),appendEntry:(customType:string,data:any)=>branch.push({type:'custom',customType,data}),sendMessage:()=>{}};
 const ctx:any={cwd,hasUI:false,sessionManager:{getBranch:()=>branch},ui:{notify:()=>{},setStatus:()=>{}}};
 embeddedDocs(pi);await handlers.get('session_start')![0]({},ctx);
 const result=await tools.get('document_import').execute('1',{path:'manual.txt'},undefined,undefined,ctx);
 branch.push({type:'message',message:{role:'toolResult',toolName:'document_import',details:result.details}});
 const id=result.details.evidence.documentId;
 const bridge=codeModeDocumentTool(pi);
 assert.match(String(await bridge.execute(['document_grep','{"query":"ABC_CTRL"}'],{})),/0x40001000/);
 await handlers.get('session_start')![0]({},ctx);
 assert.match(String(await bridge.execute(['document_read',JSON.stringify({documentId:id,pageNumber:1})],{})),/ABC_CTRL/);
 await commands.get('docs').handler('off',ctx);
 await assert.rejects(()=>bridge.execute(['document_read',JSON.stringify({documentId:id,pageNumber:1})],{}),/scope/);
 await handlers.get('session_start')![0]({},ctx);
 assert.equal(JSON.parse(String(await bridge.execute(['document_list','{}'],{}))).length,0);
 branch.pop();await handlers.get('session_tree')![0]({},ctx);
 assert.equal(JSON.parse(String(await bridge.execute(['document_list','{}'],{}))).length,1);
 await sharp({create:{width:128,height:96,channels:3,background:'white'}}).png().toFile(join(cwd,'diagram.png'));
 const imported=await tools.get('document_import').execute('2',{path:'diagram.png'},undefined,undefined,ctx);
 const imageId=imported.details.evidence.documentId;
 ctx.model={input:['text','image']};
 const viewed=await tools.get('document_view_page').execute('3',{documentId:imageId,pageNumber:1},undefined,undefined,ctx);
 const img=viewed.content.find((c:any)=>c.type==='image');
 assert.equal(img.mimeType,'image/png');
 assert.equal((await sharp(Buffer.from(img.data,'base64')).metadata()).width,128);
 ctx.model={input:['text']};
 await assert.rejects(()=>tools.get('document_view_page').execute('4',{documentId:imageId,pageNumber:1},undefined,undefined,ctx),/image-capable/);
});
